"""Application-wide constants for osu gallery."""

from __future__ import annotations

APP_NAME = "osu gallery"
APP_VERSION = "0.1.0"
DB_FILENAME = "gallery.db"

# UI dimensions
MIN_WINDOW_WIDTH = 800
MIN_WINDOW_HEIGHT = 600
SEARCH_EDIT_MIN_WIDTH = 240
SEARCH_DEBOUNCE_MS = 250
PREVIEW_PANE_WIDTH = 380
PREVIEW_PANE_MAX_WIDTH = 480
PREVIEW_HEIGHT = 384
THUMBNAIL_WIDTH = 200
THUMBNAIL_HEIGHT = 150
THUMBNAIL_WIDGET_MIN_WIDTH = 160
THUMBNAIL_WIDGET_MIN_HEIGHT = 120
IMPORT_DIALOG_MIN_WIDTH = 600
IMPORT_DIALOG_MIN_HEIGHT = 500

# Visual constants
LABEL_BG_ALPHA = 180
NORMAL_BORDER_COLOR = (180, 180, 180)
HOVER_BORDER_COLOR = (90, 150, 220)
FONT_FAMILY = "Segoe UI"

# Toast
TOAST_DEFAULT_MESSAGE = "Copied!"
TOAST_DEFAULT_DURATION_MS = 1800
TOAST_FADE_DURATION_MS = 250

# Font sizes
FONT_SIZE_TITLE = 16
FONT_SIZE_HEADER = 13
FONT_SIZE_BODY = 12
FONT_SIZE_META = 10
FONT_SIZE_LABEL = 9
FONT_SIZE_ERROR = 11

# Splitter
SPLITTER_PREVIEW_DEFAULT_WIDTH = 380
